### ISSUE TITLE
Default destination at v0.2.3

### ISSUE THREAD

**Issue by martinknor** [h4kuna/upload#2]
When i have not defined some destination, if tails in v0.2.3.
Is it possible to set default one in default config?

**Comment by martinknor** [comment]
At v0.2.2 it works

**Comment by h4kuna** [comment]
Myslím že můžeme česky. Nerozumím tomu, pokud nedefinuješ žadné destination, tak to zdechne, ok to jsem tam přidal. Proč by jsi měl chtít žádné nevyplňovat?

**Comment by martinknor** [comment]
Protože to mám většinou %wwwDir%/upload a nechci to většinou moc řešit :)

**Comment by h4kuna** [comment]
To jsem právě chtěl odstranit. Aby tě to donutilo alespoň jedno si definovat jako je v README

**Comment by h4kuna** [comment]
Ještě jinak v nette je deprecated Helpers::expand(), tím nemohu vytvořit default destination %wwwDir%/upload proto to musím nechat na uživateli. Taky jsi upravoval readme že tam byl v extension pro kontruktor parametr. Buď se musí vyplnit tento parametr a pak se nastaví nějaký default, ale taky mi to nedávalo smysl, takže radši jsem šel cestou povinné destinations.

**Comment by h4kuna** [comment]
Minimálně to odstaňuje zásadní chybu v návrhu, kdybych tu výchozí hodnotu změnil, tak to začne všem ukládat blbě.

**Comment by h4kuna** [comment]
Když už řešíme 0.2.3, upravil jsem Upload, měl by být zpětně kompatibilní, budu rád když mi napíšeš že je vše ok.
- přidal jsem kontrolu na mime type
- možnost definovat specifický upload  UploadSpecific přímo v neonu, jako jednoúčelové nahrání souboru, aby jsi tyto věci nemusel nastavovat až v místě volání.

**Comment by martinknor** [comment]
No prijde mi pohodlne tam mit prave default treba ten upload a pokud chci tak si to muzu prepsat, neprijde mi to magicke, pouziva se to dost casto a rika se tomu "Convention over configuration", ta zakladni by se pak uz menit nemela, to by byl BC break.

0.2.3 mi jede ok, az na to ze jsem prave musel pridat tu cestu

**Comment by h4kuna** [comment]
Kouknu ještě jaká je možnost si toto nadefinovat. Protože jsem to moc neviděl v nette, ale možná jsem něco přehlédnul. Dneska to nebude. Spíše o víkendu.

**Comment by h4kuna** [comment]
Je to v mastru upravené, vyzkoušej a vydám nový release.

**Comment by martinknor** [comment]
vypada to dobre, jen proc jsi to nedal normalne do toho default configu, myslim ze nette to normalne prelozi ne?

**Comment by h4kuna** [comment]
Právě že nepřeloží.

**Comment by martinknor** [comment]
Musis nad tom zavolat `$this->getContainerBuilder()->expand()`

**Comment by h4kuna** [comment]
Jseš [si tím jistý](https://api.nette.org/2.4/source-DI.ContainerBuilder.php.html#717-725)?

**Comment by martinknor** [comment]
Tak beru zpet :) mel jsem za to ze je deprecated jen to v getConfig, kazdopadne v tom pripade je to ok

**Comment by h4kuna** [comment]
Released
